version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "3000:8080"
    volumes:
      - ./:/go/src/app
    tty: true
    command: air
    restart: always