name: Run go test

on:
  pull_request:

jobs:
  test:
    name: test
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Run test
        run: |
          docker compose exec -T app go test -v -cover ./test/... -coverprofile=cover.out 2>&1 | tee > coverage.txt
          go get godoc.org/golang.org/x/tools/cmd/cover
          go get github.com/t-yuki/gocover-cobertura
          gocover-cobertura < coverage.txt > coverage.xml
          

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.0.2
        # uses: joshjohanning/CodeCoverageSummary@v1.0.2
        with:
          filename: coverage.xml
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md